### ISSUE TITLE
All icons have one color now?

### ISSUE THREAD

**Issue by tareefdev** [wyuenho/all-the-icons-dired#1]
After an update recently all icons became white with dark themes and black with light themes, instead of colorful icons. Is there any change?

![Screenshot_20210223_190739](https://user-images.githubusercontent.com/17391433/108871852-a088c300-760a-11eb-8187-75674664c102.png)

**Comment by wyuenho** [comment]
There's a new `all-the-icons-dired-monochrome` defcustom, try turning it off.

That said, your screenshot isn't not how I would expect monochrome to work. The directory icons should have the `dired-directory` face applied to it. It looks like your directory face is applied after the icons have been added.

**Comment by tareefdev** [comment]
Setting `all-the-icons-dired-monochrome` to `nil` solved the issue, colorful icons are back again now. Thanks for helping, you could close this issue.
