### ISSUE TITLE
Icons misalign on redisplay

### ISSUE THREAD

**Issue by MithicSpirit** [wyuenho/all-the-icons-dired#10]
### Describe the bug
Executing `dired-do-redisplay` on shifts the selected file(s) icons to the left edge

### To Reproduce
1. Open a folder with `dired`
2. Make sure `all-the-icons-dired` is enabled
3. Put the cursor on a file or mark it and run `dired-do-redisplay`

### Expected behavior
The icon should be left in the correct position.

### Screenshots
See here: https://github.com/hlissner/doom-emacs/issues/5579

### System
Doom Emacs on Arch Linux (using the `emacs-pgtk-native-comp-git` AUR package), though it can also be reproduced in Vanilla: https://github.com/hlissner/doom-emacs/issues/5579#issuecomment-933996556

**Comment by wyuenho** [comment]
Can you post a screenshot?

**Comment by MithicSpirit** [comment]
Sure. Before:
![image](https://user-images.githubusercontent.com/24192522/136308609-d422b919-d065-4304-b932-045535074a76.png)
After:
![image](https://user-images.githubusercontent.com/24192522/136308619-0a7d9b5d-93b2-4ee4-a344-f22818dee71b.png)
