### ISSUE TITLE
Display incorrect icons after press "l"

### ISSUE THREAD

**Issue by seagle0128** [wyuenho/all-the-icons-dired#14]
I think the root cause is the advice of `dired-do-redisplay` is missing. Please take a look at this issue. Thanks!

https://github.com/wyuenho/all-the-icons-dired/blob/5e9b097f9950cc9f86de922b07903a4e5fefc733/all-the-icons-dired.el#L113-L136

**Comment by wyuenho** [comment]
Please submit a screenshot of the problem and what is expected. If you have any stacktraces, please send over them as well.

**Comment by seagle0128** [comment]
No any stacktraces or errors since it's not a bug.

The screenshot is below. The icon was displayed incorrectly.

The workaround is 
```elisp
(with-eval-after-load 'dired-aux
        (advice-add #'dired-do-redisplay :around #'all-the-icons-dired--refresh-advice))
```
<img width="713" alt="image" src="https://user-images.githubusercontent.com/140797/156801112-84c9df5b-2d87-4068-90cc-df66e4ed4784.png">

**Comment by wyuenho** [comment]
See if master works for you
